version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGODB_URI=mongodb://mongodb:27017/gedek7
      - JWT_SECRET=910ac1e6428419a0d13dcd06a512ce515c87b493931aa6fcd5360b3196b7d8b283a73e7ab979abb4aa9e9970d46e7c6bee9c915c08a40cd525d9e114c7abd434
    depends_on:
      - mongodb
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: